#!/usr/bin/env python3
"""Install the Doppler bootstrap into whichever sitecustomize.py Python
actually imports.

Run once after installing the plugin:
    python3 ~/.hermes/plugins/doppler_secrets/setup_sitecustomize.py

The script detects the active sitecustomize.py via importlib and installs
the bootstrap there — whether that's a venv site-packages or a system-
level file.  Idempotent and safe to re-run.  Persists across Hermes
updates.
"""
import importlib.util
import site
import sys
from pathlib import Path

MARKER = "# hermes-doppler: auto-registered DopplerSource"

# Support both hyphen (hermes plugins install) and underscore (manual clone)
_PLUGIN_DIRS = ["doppler-secrets", "doppler_secrets"]

BOOTSTRAP = f'''\
{MARKER}
# Auto-generated by hermes-doppler plugin — registers the Doppler secret
# source before load_hermes_dotenv() runs. Safe to delete; the plugin
# re-creates it on next setup.
import importlib.util as _ilu
from pathlib import Path as _P
try:
    _home = _P.home() / ".hermes" / "plugins"
    _p = next((d / "__init__.py" for d in (_home / "doppler-secrets", _home / "doppler_secrets") if (d / "__init__.py").exists()), None)
    if _p:
        _s = _ilu.spec_from_file_location("doppler_secrets", str(_p))
        _m = _ilu.module_from_spec(_s)
        _s.loader.exec_module(_m)
        from agent.secret_sources.registry import register_source
        register_source(_m.DopplerSource())
except Exception:
    pass
'''


def find_sitecustomize_path() -> Path | None:
    """Return the path Python would actually load sitecustomize from.

    Falls back to the first site-packages directory when sitecustomize.py
    doesn't exist yet (first-run bootstrap).
    """
    spec = importlib.util.find_spec("sitecustomize")
    if spec and spec.origin:
        return Path(spec.origin)
    # sitecustomize.py doesn't exist yet — pick the first site-packages dir
    for sp in site.getsitepackages():
        p = Path(sp)
        if p.is_dir():
            return p / "sitecustomize.py"
    return None


def _has_bootstrap(content: str) -> bool:
    """Check if the file already has a clean Doppler bootstrap."""
    return MARKER in content and content.count("register_source") <= 2


def main() -> None:
    target = find_sitecustomize_path()
    if target is None:
        print("ERROR: could not determine sitecustomize.py location", file=sys.stderr)
        print("Python cannot find sitecustomize on this system.", file=sys.stderr)
        sys.exit(1)

    print(f"Target: {target}")

    if target.exists():
        content = target.read_text()
        if _has_bootstrap(content):
            print("Already installed — nothing to do.")
            return
        # Existing file has old/duplicate bootstraps — strip and rewrite
        # Remove everything after the initial docstring (if any) that looks
        # like a Doppler bootstrap block, then append clean version.
        lines = content.splitlines(keepends=True)
        clean_lines = []
        for line in lines:
            s = line.strip()
            # Skip known bootstrap artifacts from older setup script versions
            if any(pattern in s for pattern in [
                "spec_from_file_location(\"doppler_secrets\"",
                "spec_from_file_location('doppler_secrets'",
                "register_source(_m.DopplerSource())",
                "register_source(_mod.DopplerSource())",
                "from agent.secret_sources.registry import register_source",
                "# hermes-doppler: auto-registered DopplerSource",
                "# Auto-generated by hermes-doppler plugin",
                "from pathlib import Path as _P",
                "import importlib.util as _ilu",
            ]):
                continue
            clean_lines.append(line)
        cleaned = "".join(clean_lines).rstrip()
        target.write_text(cleaned + "\n\n" + BOOTSTRAP)
        print(f"Replaced existing Doppler bootstrap in {target}")
    else:
        # Create new file
        target.write_text(BOOTSTRAP)
        print(f"Created {target}")

    print("Restart the gateway for the change to take effect.")


if __name__ == "__main__":
    main()
