#!/usr/bin/env python3
"""Install the Doppler bootstrap into whichever sitecustomize.py Python
actually imports.

Run once after installing the plugin:
    python3 ~/.hermes/plugins/doppler_secrets/setup_sitecustomize.py

The script detects the active sitecustomize.py via importlib and appends
the bootstrap there — whether that's a venv site-packages or a system-
level file.  Idempotent and safe to re-run.  Persists across Hermes
updates.
"""
import importlib.util
import sys
from pathlib import Path

MARKER = "# hermes-doppler: auto-registered DopplerSource"

BOOTSTRAP = f'''\
{MARKER}
# Auto-generated by hermes-doppler plugin — registers the Doppler secret
# source before load_hermes_dotenv() runs. Safe to delete; the plugin
# re-creates it on next setup.
import importlib.util as _ilu
from pathlib import Path as _P
try:
    _p = _P.home() / ".hermes" / "plugins" / "doppler_secrets" / "__init__.py"
    if _p.exists():
        _s = _ilu.spec_from_file_location("doppler_secrets", str(_p))
        _m = _ilu.module_from_spec(_s)
        _s.loader.exec_module(_m)
        from agent.secret_sources.registry import register_source
        register_source(_m.DopplerSource())
except Exception:
    pass
'''


def find_sitecustomize_path() -> Path | None:
    """Return the path Python would actually load sitecustomize from."""
    spec = importlib.util.find_spec("sitecustomize")
    if spec and spec.origin:
        return Path(spec.origin)
    return None


def main() -> None:
    target = find_sitecustomize_path()
    if target is None:
        print("ERROR: could not determine sitecustomize.py location", file=sys.stderr)
        print("Python cannot find sitecustomize on this system.", file=sys.stderr)
        sys.exit(1)

    print(f"Target: {target}")

    if target.exists():
        content = target.read_text()
        if MARKER in content:
            print("Already installed — nothing to do.")
            return
        # Append to existing file
        target.write_text(content.rstrip() + "\n\n" + BOOTSTRAP)
        print(f"Appended Doppler bootstrap to {target}")
    else:
        # Create new file
        target.write_text(BOOTSTRAP)
        print(f"Created {target}")

    print("Restart the gateway for the change to take effect.")


if __name__ == "__main__":
    main()
